-- Active: 1788268010002@@127.0.0.1@3306@smartcoffee_dml_leonardo
-- SMARTCOFFEE BASE DE DADOS
-- EXECUTE SEMPRE QUE QUISER RESUTAURAR A AULA

DROP DATABASE IF EXISTS SMARTCOFFEE_DML_LEONARDO;

CREATE DATABASE SMARTCOFFEE_DML_LEONARDO;

USE SMARTCOFFEE_DML_LEONARDO;

-- TABELAS

CREATE TABLE CLIENTE (
    ID_CLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(120) UNIQUE,
    TELEFONE VARCHAR(15),
    CIDADE VARCHAR(60) NOT NULL,
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CATEGORIA (
    ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOME_CATEGORIA VARCHAR(60) NOT NULL UNIQUE
);

CREATE TABLE PRODUTO (
    ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PRODUTO VARCHAR(100) NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL,
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    ID_CATEGORIA INT NOT NULL,
    -- REFERÊNCIA DE NOMENCLATURA DE FOREIGN KEY, SEMPRE ACRESCENTAR ESSE TIPO DE DADO
    CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA)
    REFERENCES CATEGORIA(ID_CATEGORIA)
);

CREATE TABLE PEDIDO (
    ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    DATA_PEDIDO DATETIME NOT NULL,
    STATUS_PEDIDO ENUM('ABERTO', 'PREPARANDO', 'FINALIZADO', 'CANCELADO') NOT NULL,
    VALOR_TOTAL DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ID_CLIENTE INT NOT NULL,
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE TABLE ITEM_PEDIDO (
    ID_ITEM INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    PRECO_UNITARIO DECIMAL(10,2) NOT NULL,
    OBSERVACAO VARCHAR(150),
    CONSTRAINT FK_ITEM_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO),
    CONSTRAINT FK_ITEM_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID_PRODUTO)
);

CREATE TABLE FORMA_PAGAMENTO (
    ID_FORMA_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE PAGAMENTO (
    ID_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT NOT NULL,
    ID_FORMA_PAGAMENTO INT NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL,
    DATA_PAGAMENTO DATETIME,
    CONSTRAINT FK_PAGAMENTO_PEDIDO FOREIGN KEY (ID_PEDIDO)
    REFERENCES PEDIDO (ID_PEDIDO),
    CONSTRAINT FK_FORMA_PAGAMENTO FOREIGN KEY (ID_FORMA_PAGAMENTO) REFERENCES FORMA_PAGAMENTO (ID_FORMA_PAGAMENTO)
);

-- INSERÇÃO DE DADOS

INSERT INTO CLIENTE (NOME, EMAIL, TELEFONE, CIDADE, ATIVO, DATA_CADASTRO) VALUES
('ELIANA SILVA', 'ANA@EMAIL.COM', '19999999001', 'LIMEIRA', TRUE, NULL),
('BRUNO SOUZA', 'BRUNO@EMAIL.COM', '19999999002', 'CAMPINAS', TRUE, NULL),
('ANTONIO PEREIRA', 'CARLOS@EMAIL.COM', '19999999003', 'CORDEIRO', TRUE, NULL),
('DANIELA COSTA', 'DANIELA@EMAIL.COM', '19999999004', 'LIMEIRA', TRUE, NULL),
('ELIAS MORAES', 'ELIAS@EMAIL.COM', '19999999005', 'PIRACICABA', TRUE, NULL),
('FABIANA ALMEIDA', 'FABIANA@EMAIL.COM', '19999999006', 'LIMEIRA', TRUE, NULL),
('GUSTAVO LIMA', 'GUSTAVO@EMAIL.COM', '19999999007', 'LIMEIRA', TRUE, NULL),
('NICOLLAS LOMBAS', 'HUGO@EMAIL.COM', '19999999008', 'LIMEIRA', TRUE, NULL),
('ISABELA CAMPOS', 'ISABELA@EMAIL.COM', '19999999009', 'LIMEIRA', TRUE, NULL);

INSERT INTO CATEGORIA (NOME_CATEGORIA) VALUES
('CAFÉ'),
('SANDUÍCHES'),
('BEBIDAS QUENTES'),
('BEBIDAS GELADAS'),
('SOBREMESAS'),
('LANCHES'),
('SALGADOS'),
('DOCES');

SELECT * FROM CATEGORIA;

INSERT INTO PRODUTO (NOME_PRODUTO, PRECO, ATIVO, ID_CATEGORIA) VALUES
('CAFÉ', 5.00, 1, 1),
('SANDUÍCHES', 15.00, 1, 2),
('BEBIDAS QUENTES', 7.00, 1, 3),
('BEBIDAS GELADAS', 8.00, 1, 4),
('SOBREMESAS', 10.00, 1, 5),
('LANCHES', 12.00, 1, 6),
('SALGADOS', 6.00, 1, 7),
('DOCES', 4.00, 1, 8);

SELECT * FROM PRODUTO;

INSERT INTO PEDIDO (DATA_PEDIDO, STATUS_PEDIDO, VALOR_TOTAL, ID_CLIENTE) VALUES
('2024-06-01 10:00:00', 'ABERTO', 0.00, 1),
('2024-06-01 11:00:00', 'PREPARANDO', 0.00, 2),
('2024-06-01 12:00:00', 'FINALIZADO', 0.00, 3),
('2024-06-01 13:00:00', 'CANCELADO', 0.00, 4),
('2024-06-01 14:00:00', 'ABERTO', 0.00, 5),
(NOW(), 'ABERTO', 0.00, 8);

SET @PEDIDO = LAST_INSERT_ID();
SELECT @PEDIDO;

SELECT * FROM PEDIDO;

INSERT INTO ITEM_PEDIDO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE, PRECO_UNITARIO, OBSERVACAO) VALUES
(1, 1, 2, 5.00, 'Sem açúcar'),
(1, 2, 1, 15.00, 'Com queijo extra'),
(2, 3, 1, 7.00, NULL),
(2, 4, 2, 8.00, 'Com gelo'),
(3, 5, 1, 10.00, NULL),
(3, 6, 1, 12.00, 'Sem maionese'),
(4, 7, 3, 6.00, NULL),
(4, 8, 2, 4.00, 'Com chocolate extra'),
(5, 1, 1, 5.00, NULL);

SELECT * FROM ITEM_PEDIDO;

INSERT INTO FORMA_PAGAMENTO (DESCRICAO) VALUES
('DINHEIRO'),
('CARTÃO DE CRÉDITO'),
('CARTÃO DE DÉBITO'),
('PIX');

INSERT INTO PAGAMENTO (ID_PEDIDO, ID_FORMA_PAGAMENTO, VALOR, DATA_PAGAMENTO) VALUES
(1, 1, 25.00, '2024-06-01 10:30:00'),
(2, 2, 23.00, '2024-06-01 11:30:00'),
(3, 3, 22.00, '2024-06-01 12:30:00'),
(4, 4, 18.00, '2024-06-01 13:30:00'),
(5, 1, 5.00, '2024-06-01 14:30:00');

-- EX 1° UPDATE OU ATUALIZAÇÕES DE DADOS
UPDATE CLIENTE
SET TELEFONE = '199999999928'
WHERE ID_CLIENTE = 3; -- DETERMINAR O COMANDO WHERE SEMPRE!

-- EX 2° ATUALIZANDO VÁRIOS CAMPOS
UPDATE CLIENTE
SET TELEFONE = '1999999999999', CIDADE = 'Piracicaba'
WHERE ID_CLIENTE = 5;

-- EX 3° ATUALIZANDO VÁRIOS REGISTROS
UPDATE PRODUTO
SET PRECO = PRECO * 1.05
WHERE ID_CATEGORIA = 1;

-- EX 4° ATUALIZANDO SEM WHERE
-- UPDATE PRODUTO
-- SET PRECO = 1.00;
-- CUIDADO AO UTILIZAR ESSA LINHA. (Altera para todos.)

-- EX 5° ATUALIZANDO CONDICIONAIS
UPDATE PRODUTO
SET PRECO = CASE
    WHEN PRECO < 10 THEN PRECO * 1.10 -- TRADUÇÃO: QUANDO PRECO MENOR QUE 10 ENTÃO PRECO * 1.10
    ELSE PRECO * 1.05 -- SE NÃO PRECO * 1.05
END
WHERE ATIVO = TRUE;

-- EX 6° ATUALIZANDO PARA NULL
UPDATE CLIENTE
SET TELEFONE = NULL
WHERE ID_CLIENTE = 5;

-- EX 1° EXCLUIR REGISTROS OU DADOS
DELETE FROM CATEGORIA
WHERE ID_CATEGORIA = 2;

-- EX 2° EXCLUIR REGISTROS COM ESTRUTURA LÓGICA
UPDATE PRODUTO
SET ATIVO = FALSE
WHERE ID_PRODUTO = 17;

-- LIMPAR TABELA OU REMOVER TODOS OS REGISTROS
TRUNCATE TABLE CLIENTE;


SELECT * FROM CATEGORIA; -- CONSULTAR INFORMAÇÕES NO BANCO
-- CONSULTA POR ID
SELECT * FROM cliente
WHERE ID_CLIENTE = 4;

-- MENSAGEM DE SUCESSO
SELECT 'BANCO DE DADOS SMARTCOFFEE_DML_BRUNO CRIADO COM SUCESSO!' AS Mensagem;